### ISSUE TITLE
Poetry install fails

### ISSUE THREAD

**Issue by silvio-liqi** [aleorda/rock-paper-scissor#4]
Running `poetry install` fails with the following error

![image](https://user-images.githubusercontent.com/126506158/223061272-51318636-d445-4a99-be2a-c2dee74ef8a7.png)

**Comment by aleorda** [comment]
I changed the package indicated in the pyproject.toml

commit: https://github.com/aleorda/rock-paper-scissor/commit/cc02a5d212a948dce74e1c7909fd7369becb1d90

Can you please check if it works?

**Comment by silvio-liqi** [comment]
Working!
